name: 'dremix1'

services:
  remix:
    #    image: app-dremix1-node:latest
    build:
      context: ./docker/node
      args:
        - UID=1000
        - GID=1000
        - USER_NAME=dev
    user: 1000:1000
    volumes:
      - ./source:/app
    ports:
      - 3000:3000
    command:
      - npm
      - run
      - dev
   
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=remix-task

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=123
    ports:
      - 3001:80
